### ISSUE TITLE
wasmedge - invalid pointer found on stack

### ISSUE THREAD

**Issue by loredanacirstea** [ark-us/wasmx#153]
This error happens sometimes and the chain halts with a segfault. not clear when or why.

* the error points to `C.uint64_t(cost)) `, but I think the issue is with `unsafe.Pointer(uintptr(index)),`

I changed the wasmedge-go code to:
```
	index := hostfuncMgr.add(fn, additional)
	fmt.Println("--NewFunction-0-", ftype, "-1-", fn, "-2-", "-3-", cost, "-4-", index)
	ccost := C.uint64_t(cost)
	fmt.Println("--ccost--", ccost)
	usfptr := unsafe.Pointer(uintptr(index))
	fmt.Println("--usfptr--", usfptr)
	hostfnwrapp := C.wasmedgego_HostFuncWrapper(C.wasmedgego_HostFuncInvoke)
	fmt.Println("--hostfnwrapp--", hostfnwrapp)
	function := C.WasmEdge_FunctionInstanceCreateBinding(

```
and reproduced the error. last print was `fmt.Println("--usfptr--", usfptr)`, but the invalid pointer was `usfptr`
```
--NewFunction-0- &{0x60000129fc50 true} -1- 0x105b793d0 -2- -3- 0 -4- 277
--ccost-- 0
--usfptr-- 0x115
--hostfnwrapp-- &[]
--NewFunction-0- &{0x60000129fc50 true} -1- 0x105b79630 -2- -3- 0 -4- 278
--ccost-- 0
--usfptr-- 0x116
runtime: bad pointer in frame github.com/second-state/WasmEdge-go/wasmedge.NewFunction at 0x140042128a0: 0x116
fatal error: invalid pointer found on stack

runtime stack: ...
```

```
BuildWasmxEnv2
mythos/v1/x/wasmx/vm/ops_wasmx_2.go:1304 // or 1266 or any other function
-> env.AddFunction("ed25519PubToHex", wasmedge.NewFunction(functype_i32_i32, ed25519PubToHex, context, 0))

github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/instance.go:276
github.com/second-state/WasmEdge-go/wasmedge.NewFunction

function := C.WasmEdge_FunctionInstanceCreateBinding(
		ftype._inner,
		C.wasmedgego_HostFuncWrapper(C.wasmedgego_HostFuncInvoke),
		unsafe.Pointer(uintptr(index)),
		nil,
		C.uint64_t(cost)) /////// 276 // constant error

runtime/cgocall.go:450
github.com/second-state/WasmEdge-go/wasmedge.NewFunction.func1

runtime/cgocall.go:461
runtime.cgoCheckPointer

runtime/asm_arm64.s:316
goroutine 4184 [running, locked to thread]:
runtime.cgoCheckArg
```

* full error
```
runtime: bad pointer in frame github.com/second-state/WasmEdge-go/wasmedge.NewFunction.func1 at 0x14003b98920: 0x1da
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0x1039c4c0a?, 0x0?})
	runtime/panic.go:1077 +0x40 fp=0x1760214e0 sp=0x1760214b0 pc=0x100f0c260
runtime.adjustpointers(0x176021748?, 0x0?, 0x0?, {0x0?, 0x0?})
	runtime/stack.go:627 +0x19c fp=0x176021520 sp=0x1760214e0 pc=0x100f2699c
runtime.adjustframe(0x176021748, 0x176021628)
	runtime/stack.go:684 +0xd8 fp=0x1760215b0 sp=0x176021520 pc=0x100f26ab8
runtime.copystack(0x1400157c4e0, 0x20000)
	runtime/stack.go:935 +0x2d4 fp=0x1760218b0 sp=0x1760215b0 pc=0x100f272e4
runtime.shrinkstack(0x1400157c4e0)
	runtime/stack.go:1218 +0x124 fp=0x1760218d0 sp=0x1760218b0 pc=0x100f27ef4
runtime.newstack()
	runtime/stack.go:1066 +0x2a4 fp=0x176021a80 sp=0x1760218d0 pc=0x100f276d4
traceback: unexpected SPWRITE function runtime.morestack
runtime.morestack()
	runtime/asm_arm64.s:316 +0x70 fp=0x176021a80 sp=0x176021a80 pc=0x100f41f10

goroutine 1271 [running, locked to thread]:
runtime.cgoCheckArg(0x1046635a0?, 0x1400367f5c0?, 0x1?, 0x1?, {0x103a39ee5?, 0x32?})
	runtime/cgocall.go:461 +0x4a0 fp=0x14003b98870 sp=0x14003b98870 pc=0x100ed8dd0
runtime.cgoCheckPointer({0x1046635a0, 0x1400367f5c0}, {0x0, 0x0})
	runtime/cgocall.go:450 +0x144 fp=0x14003b988c0 sp=0x14003b98870 pc=0x100ed88d4
github.com/second-state/WasmEdge-go/wasmedge.NewFunction.func1(0x109f89f20?, 0x104e226f8?, 0x1049f7740?)
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/instance.go:276 +0x58 fp=0x14003b98930 sp=0x14003b988c0 pc=0x1022bc588
github.com/second-state/WasmEdge-go/wasmedge.NewFunction(0x1400367f540, 0x10381e716?, {0x1049f7740?, 0x140030b8480?}, 0x1?)
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/instance.go:276 +0x4c fp=0x14003b98980 sp=0x14003b98930 pc=0x1022bc48c
mythos/v1/x/wasmx/vm.BuildWasmxEnv2(0x10480e4e0?)
	mythos/v1/x/wasmx/vm/ops_wasmx_2.go:1265 +0x1bc fp=0x14003b98a20 sp=0x14003b98980 pc=0x1026f5c4c
mythos/v1/x/wasmx/vm.InitiateWasmxEnv2(0x140030b8480, 0x1400129bf20?, 0x1400367f460?)
	mythos/v1/x/wasmx/vm/initiate.go:67 +0xc8 fp=0x14003b98ad0 sp=0x14003b98a20 pc=0x1026d3d78
mythos/v1/x/wasmx/vm.initiateWasmDeps(0x1400168a218?, 0x1046d2e00?, {0x14003030320, 0x1, 0x10468f060?})
	mythos/v1/x/wasmx/vm/vm.go:100 +0x228 fp=0x14003b98b80 sp=0x14003b98ad0 pc=0x1026f9d98
mythos/v1/x/wasmx/vm.InitiateWasm(0x1400367f460?, {0x1400132e660, 0x5c}, {0x0, 0x0, 0x0}, {0x14003030320, 0x1, 0x1})
	mythos/v1/x/wasmx/vm/vm.go:63 +0x2b8 fp=0x14003b98cc0 sp=0x14003b98b80 pc=0x1026f9868
mythos/v1/x/wasmx/vm.ContractContext.Execute({0x0, 0x0, 0x0, 0x0, {{{0x14001e839b0, 0x14, 0x30}, {0x10381dd1a, 0x6}}, {0x1400367f428, ...}, ...}}, ...)
	mythos/v1/x/wasmx/vm/types.go:68 +0x1e0 fp=0x14003b98e50 sp=0x14003b98cc0 pc=0x1026f9100
mythos/v1/x/wasmx/vm.WasmxCall(0x14000fe5200, {{{0x14001e839b0, 0x14, 0x30}, {0x10381dd1a, 0x6}}, {{0x14003d93020, 0x14, 0x15}, {0x10381dd1a, ...}}, ...})
	mythos/v1/x/wasmx/vm/ops_common.go:247 +0x1104 fp=0x14003b9bbf0 sp=0x14003b98e50 pc=0x1026d9dc4
mythos/v1/x/wasmx/vm.wasmxCall({0x1049f7740?, 0x14000fe5200}, 0x7f?, {0x14003681170?, 0x1046d1bc0?, 0x1400367f1e8?})
	mythos/v1/x/wasmx/vm/ops_wasmx_2.go:238 +0x8b4 fp=0x14003b9ccc0 sp=0x14003b9bbf0 pc=0x1026efb04
github.com/second-state/WasmEdge-go/wasmedge.wasmedgego_HostFuncInvokeImpl(0x14003e42e18?, 0x100f1768c?, 0x176021db0, 0x600003af0000, 0x1, 0x600003af0020, 0x1)
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/hostfunc.go:82 +0xd8 fp=0x14003b9cde0 sp=0x14003b9ccc0 pc=0x1022ba678
_cgoexp_fbad98d1796e_wasmedgego_HostFuncInvokeImpl(0x176021b88)
	_cgo_gotypes.go:3263 +0x40 fp=0x14003b9ce30 sp=0x14003b9cde0 pc=0x1022c5670
runtime.cgocallbackg1(0x1022c5630, 0x1400330b010?, 0x0)
	runtime/cgocall.go:329 +0x23c fp=0x14003b9cf10 sp=0x14003b9ce30 pc=0x100ed858c
runtime.cgocallbackg(0x14003e42fe8?, 0x100f3e1a8?, 0x1400157c4e0?)
	runtime/cgocall.go:245 +0xec fp=0x14003b9cfa0 sp=0x14003b9cf10 pc=0x100ed82bc
runtime.cgocallbackg(0x1022c5630, 0x176021b88, 0x0)
	<autogenerated>:1 +0x1c fp=0x14003b9cfd0 sp=0x14003b9cfa0 pc=0x100f464bc
runtime.cgocallback(0x1400330b048, 0x1022b4764, 0x10376476c)
	runtime/asm_arm64.s:1105 +0xb0 fp=0x14003b9d000 sp=0x14003b9cfd0 pc=0x100f44310
runtime.systemstack_switch()
	runtime/asm_arm64.s:200 +0x8 fp=0x14003b9d010 sp=0x14003b9d000 pc=0x100f41dd8
runtime.cgocall(0x10376476c, 0x1400330b088)
	runtime/cgocall.go:175 +0x70 fp=0x14003b9d050 sp=0x14003b9d010 pc=0x100ed8170
github.com/second-state/WasmEdge-go/wasmedge._Cfunc_WasmEdge_VMExecute(0x16a358200, {0x4, 0x10380d0ad}, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:2600 +0x34 fp=0x14003b9d080 sp=0x14003b9d050 pc=0x1022b4764
github.com/second-state/WasmEdge-go/wasmedge.(*VM).Execute.func1(0x0?, {0x0?, 0x10380d0ad?}, 0x1021c0fb8?, {0x109fcc420?, 0x0, 0x14003e43208?}, 0x1026f9180?, {0x109fcc420?, 0x0, ...})
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/vm.go:246 +0xa4 fp=0x14003b9d100 sp=0x14003b9d080 pc=0x1022c31e4
github.com/second-state/WasmEdge-go/wasmedge.(*VM).Execute(0x7b000001021c10d0?, {0x10380d0ad, 0x4}, {0x0, 0x0, 0x0})
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/vm.go:246 +0x110 fp=0x14003b9d1c0 sp=0x14003b9d100 pc=0x1022c3070
mythos/v1/x/wasmx/vm.ExecuteDefaultContract(0x10480e660?, 0x1400129bf50?, {0x103837e11, 0x7}, {0x6?, 0x0?, 0x140001a1b00?})
	mythos/v1/x/wasmx/vm/initiate.go:220 +0xc4 fp=0x14003b9d210 sp=0x14003b9d1c0 pc=0x1026d4e44
mythos/v1/x/wasmx/vm.ContractContext.Execute({0x0, 0x0, 0x0, 0x0, {{{0x14002b1c7b0, 0x14, 0x30}, {0x10381dd1a, 0x6}}, {0x14003a7cc2b, ...}, ...}}, ...)
	mythos/v1/x/wasmx/vm/types.go:78 +0x328 fp=0x14003b9d3a0 sp=0x14003b9d210 pc=0x1026f9248
mythos/v1/x/wasmx/vm.WasmxCall(0x140015bd680, {{{0x140036ddda0, 0x14, 0x15}, {0x10381dd1a, 0x6}}, {{0x14003d93020, 0x14, 0x15}, {0x10381dd1a, ...}}, ...})
	mythos/v1/x/wasmx/vm/ops_common.go:247 +0x1104 fp=0x14003ba0140 sp=0x14003b9d3a0 pc=0x1026d9dc4
mythos/v1/x/wasmx/vm.wasmxCall({0x1049f7740?, 0x140015bd680}, 0x7f?, {0x14004ecc010?, 0x2?, 0x14004ec5f50?})
	mythos/v1/x/wasmx/vm/ops_wasmx_2.go:238 +0x8b4 fp=0x14003ba1210 sp=0x14003ba0140 pc=0x1026efb04
github.com/second-state/WasmEdge-go/wasmedge.wasmedgego_HostFuncInvokeImpl(0x140014d9f4c?, 0x0?, 0x1760227f0, 0x600003af4000, 0x1, 0x600003af4020, 0x1)
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/hostfunc.go:82 +0xd8 fp=0x14003ba1330 sp=0x14003ba1210 pc=0x1022ba678
_cgoexp_fbad98d1796e_wasmedgego_HostFuncInvokeImpl(0x1760225c8)
	_cgo_gotypes.go:3263 +0x40 fp=0x14003ba1380 sp=0x14003ba1330 pc=0x1022c5670
runtime.cgocallbackg1(0x1022c5630, 0x14003e47560?, 0x0)
	runtime/cgocall.go:329 +0x23c fp=0x14003ba1460 sp=0x14003ba1380 pc=0x100ed858c
runtime.cgocallbackg(0x14004cbf538?, 0x100f3e1a8?, 0x1400157c4e0?)
	runtime/cgocall.go:245 +0xec fp=0x14003ba14f0 sp=0x14003ba1460 pc=0x100ed82bc
runtime.cgocallbackg(0x1022c5630, 0x1760225c8, 0x0)
	<autogenerated>:1 +0x1c fp=0x14003ba1520 sp=0x14003ba14f0 pc=0x100f464bc
runtime.cgocallback(0x1400330f598, 0x1022b4764, 0x10376476c)
	runtime/asm_arm64.s:1105 +0xb0 fp=0x14003ba1550 sp=0x14003ba1520 pc=0x100f44310
runtime.systemstack_switch()
	runtime/asm_arm64.s:200 +0x8 fp=0x14003ba1560 sp=0x14003ba1550 pc=0x100f41dd8
runtime.cgocall(0x10376476c, 0x1400330f5d8)
	runtime/cgocall.go:175 +0x70 fp=0x14003ba15a0 sp=0x14003ba1560 pc=0x100ed8170
github.com/second-state/WasmEdge-go/wasmedge._Cfunc_WasmEdge_VMExecute(0x649857c00, {0x8, 0x10383a265}, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:2600 +0x34 fp=0x14003ba15d0 sp=0x14003ba15a0 pc=0x1022b4764
github.com/second-state/WasmEdge-go/wasmedge.(*VM).Execute.func1(0x0?, {0x0?, 0x10383a265?}, 0x100ee0efc?, {0x109fcc420?, 0x0, 0x14004cbf6f8?}, 0x40?, {0x109fcc420?, 0x0, ...})
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/vm.go:246 +0xa4 fp=0x14003ba1650 sp=0x14003ba15d0 pc=0x1022c31e4
github.com/second-state/WasmEdge-go/wasmedge.(*VM).Execute(0xca00014004cbf758?, {0x10383a265, 0x8}, {0x0, 0x0, 0x0})
	github.com/second-state/WasmEdge-go@v0.13.4/wasmedge/vm.go:246 +0x110 fp=0x14003ba1710 sp=0x14003ba1650 pc=0x1022c3070
mythos/v1/x/wasmx/vm.ExecuteFSM(0x10480e660?, 0x1400129bf50?, {0x10383a265, 0x8}, {0x10468f060?, 0x0?, 0x14001eac460?})
	mythos/v1/x/wasmx/vm/initiate.go:231 +0x108 fp=0x14003ba1760 sp=0x14003ba1710 pc=0x1026d5038
mythos/v1/x/wasmx/vm.ExecuteWasmInterpreted(_, {_, _}, {{0x104e73780, 0x109fcc420}, {0x104e950f0, 0x140015b1f00}, {{0x0, 0x0}, {0x140011c5e80, ...}, ...}, ...}, ...)
	mythos/v1/x/wasmx/vm/vm.go:317 +0xa9c fp=0x14003ba20e0 sp=0x14003ba1760 pc=0x1026fb28c
mythos/v1/x/wasmx/keeper.(*WasmxEngine).ExecuteEntryPoint(_, {{0x104e73780, 0x109fcc420}, {0x104e950f0, 0x140015b1f00}, {{0x0, 0x0}, {0x140011c5e80, 0xd}, 0x13, ...}, ...}, ...)
	mythos/v1/x/wasmx/keeper/vm.go:163 +0x294 fp=0x14003ba28a0 sp=0x14003ba20e0 pc=0x1036ac544
mythos/v1/x/wasmx/keeper.(*Keeper).ExecuteEntryPoint(_, {{0x104e73780, 0x109fcc420}, {0x104e950f0, 0x140015b1f00}, {{0x0, 0x0}, {0x140011c5e80, 0xd}, 0x13, ...}, ...}, ...)
	mythos/v1/x/wasmx/keeper/contract.go:684 +0x928 fp=0x14003ba4740 sp=0x14003ba28a0 pc=0x103694eb8
mythos/v1/x/network/keeper.(*Keeper).ExecuteEntryPoint(_, {{0x104e73780, 0x109fcc420}, {0x104e950f0, 0x140015b1f00}, {{0x0, 0x0}, {0x140011c5e80, 0xd}, 0x13, ...}, ...}, ...)
	mythos/v1/x/network/keeper/wasmxwrap.go:64 +0x208 fp=0x14003ba4c30 sp=0x14003ba4740 pc=0x102abb0d8
mythos/v1/x/network/keeper.(*Keeper).startTimeoutInternal.func1({0x104e73d30?, 0x14003199ce0?})
	mythos/v1/x/network/keeper/keeper_timeout.go:91 +0x108 fp=0x14003ba53c0 sp=0x14003ba4c30 pc=0x102ab62a8
mythos/v1/x/network/keeper.(*ActionExecutor).Execute(0x140018dc210, {0x104e73d30, 0x14001a96990}, 0x140014e6960?, 0x14004cc3ed0)
	mythos/v1/x/network/keeper/executor.go:192 +0x1e8 fp=0x14003ba5e80 sp=0x14003ba53c0 pc=0x102ab07c8
mythos/v1/x/network/keeper.(*Keeper).startTimeoutInternal(0x140005fdb98, {0x14001a55c70, 0xca}, 0x140038f1c80, {0x2?, 0x2?})
	mythos/v1/x/network/keeper/keeper_timeout.go:104 +0x174 fp=0x14003ba5f00 sp=0x14003ba5e80 pc=0x102ab60f4
mythos/v1/x/network/keeper.(*Keeper).startTimeoutInternalGoroutine.func1()
	mythos/v1/x/network/keeper/keeper_timeout.go:49 +0x114 fp=0x14003ba5fd0 sp=0x14003ba5f00 pc=0x102ab5d44
runtime.goexit()
	runtime/asm_arm64.s:1197 +0x4 fp=0x14003ba5fd0 sp=0x14003ba5fd0 pc=0x100f44404
created by mythos/v1/x/network/keeper.(*Keeper).startTimeoutInternalGoroutine in goroutine 1298
	mythos/v1/x/network/keeper/keeper_timeout.go:47 +0x258

...... [too long[

```

**Comment by loredanacirstea** [comment]
we use wazero now. wasmedge backend is used to show easy replacement of wasm engine
