### ISSUE TITLE
Nil pointer error when using both eWasm and EVM interpreter contracts

### ISSUE THREAD

**Issue by loredanacirstea** [ark-us/wasmx#55]
```
{
  "error": "Query failed with (6): rpc error: code = Unknown desc = recovered: runtime error: invalid memory address or nil pointer dereference\nstack:\ngoroutine 17312 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x103558020, 0x104c289b0})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/recovery.go:71 +0x24\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x103558020?, 0x104c289b0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/recovery.go:39 +0x34\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x103558020, 0x104c289b0}, 0x140005c6c78?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/recovery.go:28 +0x38\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x103558020, 0x104c289b0}, 0x1038837c0?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/recovery.go:33 +0x60\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/baseapp.go:633 +0xa8\npanic({0x103558020, 0x104c289b0})\n\truntime/panic.go:884 +0x204\nmythos/v1/x/wasmx/vm.callStatic({0x10344a080?, 0x140003a5800}, 0x7f?, {0x140060a48a0, 0x6, 0x14002ba5220?})\n\tmythos/v1/x/wasmx/vm/ops_ewasm.go:567 +0x238\ngithub.com/second-state/WasmEdge-go/wasmedge.wasmedgego_HostFuncInvokeImpl(0x140048d3d48?, 0x100da49b4?, 0x16f1b6978, 0x600001778180, 0x6, 0x6000022535c0, 0x1)\n\tgithub.com/second-state/WasmEdge-go@v0.11.2/wasmedge/hostfunc.go:82 +0xd8\ngithub.com/second-state/WasmEdge-go/wasmedge._Cfunc_WasmEdge_VMExecute(0x12b1b9a00, {0xb, 0x102560c57}, 0x0, 0x0, 0x0, 0x0)\n\t_cgo_gotypes.go:2577 +0x38\ngithub.com/second-state/WasmEdge-go/wasmedge.(*VM).Execute.func1(0x0?, {0x0?, 0x102560c57?}, 0x7400008428?, {0x104ca2648?, 0x0, 0x0?}, 0x0?, {0x104ca2648?, 0x0, ...})\n\tgithub.com/second-state/WasmEdge-go@v0.11.2/wasmedge/vm.go:246 +0xa4\ngithub.com/second-state/WasmEdge-go/wasmedge.(*VM).Execute(0x140003a5800?, {0x102560c57, 0xb}, {0x0, 0x0, 0x0})\n\tgithub.com/second-state/WasmEdge-go@v0.11.2/wasmedge/vm.go:246 +0x110\nmythos/v1/x/wasmx/vm.ExecuteWasm({{0x1038737b0, 0x140000581d8}, {0x1038837c0, 0x140018d8c80}, {{0xb, 0x0}, {0x14000148960, 0xe}, 0x6de, {0xc8c3438, ...}, ...}, ...}, ...)\n\tmythos/v1/x/wasmx/vm/vm.go:291 +0x6ac\nmythos/v1/x/wasmx/keeper.WasmxEngine.Instantiate({{_, _}, _}, {{0x1038737b0, 0x140000581d8}, {0x1038837c0, 0x140018d8c80}, {{0xb, 0x0}, {0x14000148960, ...}, ...}, ...}, ...)\n\tmythos/v1/x/wasmx/keeper/vm.go:66 +0x1b4\nmythos/v1/x/wasmx/keeper.Keeper.instantiateInternal({{0x103889038, 0x1400124bb30}, {0x10385ae20, 0x14000e53570}, {0x10385ae20, 0x0}, {{0x103882db0, 0x1400124bb30}, 0x140001b6808, {0x10385ae20, ...}, ...}, ...}, ...)\n\tmythos/v1/x/wasmx/keeper/contract.go:380 +0x958\nmythos/v1/x/wasmx/keeper.Keeper.instantiate({{0x103889038, 0x1400124bb30}, {0x10385ae20, 0x14000e53570}, {0x10385ae20, 0x0}, {{0x103882db0, 0x1400124bb30}, 0x140001b6808, {0x10385ae20, ...}, ...}, ...}, ...)\n\tmythos/v1/x/wasmx/keeper/contract.go:291 +0x200\nmythos/v1/x/wasmx/keeper.Keeper.Instantiate(...)\n\tmythos/v1/x/wasmx/keeper/contract.go:48\nmythos/v1/x/wasmx/keeper.msgServer.InstantiateContract({{{0x103889038, 0x1400124bb30}, {0x10385ae20, 0x14000e53570}, {0x10385ae20, 0x0}, {{0x103882db0, 0x1400124bb30}, 0x140001b6808, {0x10385ae20, ...}, ...}, ...}}, ...)\n\tmythos/v1/x/wasmx/keeper/msg_server.go:97 +0x6b0\nmythos/v1/x/wasmx/types._Msg_InstantiateContract_Handler.func1({0x103873820, 0x14005e4ac90}, {0x1037e2840?, 0x140061ef260})\n\tmythos/v1/x/wasmx/types/tx.pb.go:1366 +0x74\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x103874930, 0x14004600dc0}, {0x140048d8728?, 0x10190888c?}, 0x103834360?, 0x140012d1c20)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/msg_service_router.go:113 +0xb8\nmythos/v1/x/wasmx/types._Msg_InstantiateContract_Handler({0x103838d00?, 0x1400106f900}, {0x103874930, 0x14004600dc0}, 0x1038450a0, 0x140062e6600)\n\tmythos/v1/x/wasmx/types/tx.pb.go:1368 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x1038737b0, 0x140000581d8}, {0x1038837c0, 0x140018d8c80}, {{0xb, 0x0}, {0x14000148960, 0xe}, 0x6de, {0xc8c3438, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/msg_service_router.go:126 +0x2bc\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x1038737b0, 0x140000581d8}, {0x1038837c0, 0x140018d8c80}, {{0xb, 0x0}, {0x14000148960, 0xe}, 0x6de, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/baseapp.go:779 +0x490\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0x14000d45dc0, 0x2, {0x140056c1400, 0x3d5, 0x400})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/baseapp.go:719 +0x8f4\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(0x10?, {0x140056c1400?, 0x1?, 0x14005f909a0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/test_helpers.go:25 +0x30\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x10388fe58, 0x14002b9e5e0}, 0x0, {0x0, 0x0}, {0x103889038, 0x1400124bb30}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/x/auth/tx/service.go:131 +0x108\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x103715ee0?, 0x14000da1340}, {0x103874930, 0x140046002c0}, 0x140052979f0, 0x0)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/types/tx/service.pb.go:926 +0x170\ngithub.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x1038737b0, 0x140000581d8}, {0x1038837c0, 0x14005e81480}, {{0xb, 0x0}, {0x14000148960, 0xe}, 0x6de, {0xc8c3438, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/grpcrouter.go:82 +0x144\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0x14000d45dc0, 0x14002b99470, {{0x140044fa000, 0x3d8, 0x800}, {0x140011f3860, 0x23}, 0x6de, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:562 +0xfc\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0x14000d45dc0, {{0x140044fa000, 0x3d8, 0x800}, {0x140011f3860, 0x23}, 0x6de, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:406 +0x8bc\ngithub.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0x14000d36e40, {{0x140044fa000, 0x3d8, 0x800}, {0x140011f3860, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:256 +0x144\ngithub.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x14002ba4ef0?, {{0x140044fa000, 0x3d8, 0x800}, {0x140011f3860, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:159 +0x5c\ngithub.com/tendermint/tendermint/rpc/core.ABCIQuery(0x8?, {0x140011f3860?, 0x14000186300?}, {0x140044fa000?, 0x1400459aa78?, 0x100e00588?}, 0x2?, 0x2?)\n\tgithub.com/tendermint/tendermint@v0.34.24/rpc/core/abci.go:20 +0x84\nreflect.Value.call({0x10358b9a0?, 0x103847c68?, 0x1400459b198?}, {0x102555e8a, 0x4}, {0x14003885780, 0x5, 0x10170db24?})\n\treflect/value.go:584 +0x688\nreflect.Value.Call({0x10358b9a0?, 0x103847c68?, 0x7f6?}, {0x14003885780?, 0x140052978b0?, 0x140041e6c40?})\n\treflect/value.go:368 +0x90\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x1038706f0, 0x140012d0af8}, 0x14001903800)\n\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_json_handler.go:108 +0xd90\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x1038706f0?, 0x140012d0af8?}, 0x1b?)\n\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_json_handler.go:140 +0x70\nnet/http.HandlerFunc.ServeHTTP(0x5001?, {0x1038706f0?, 0x140012d0af8?}, 0x100d6dc4c?)\n\tnet/http/server.go:2109 +0x38\nnet/http.(*ServeMux).ServeHTTP(0x140001283c0?, {0x1038706f0, 0x140012d0af8}, 0x14001903800)\n\tnet/http/server.go:2487 +0x140\ngithub.com/rs/cors.(*Cors).Handler.func1({0x1038706f0, 0x140012d0af8}, 0x14001903800)\n\tgithub.com/rs/cors@v1.8.2/cors.go:231 +0x1e4\nnet/http.HandlerFunc.ServeHTTP(0x14000088900?, {0x1038706f0?, 0x140012d0af8?}, 0x1037eb8c0?)\n\tnet/http/server.go:2109 +0x38\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x103859720?, 0x14001dfbfc0?}, 0x10?}, {0x1038706f0?, 0x140012d0af8}, 0x14001903800)\n\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_server.go:256 +0x134\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x1038721f0?, 0x14000de4fc0}, 0x14001903800)\n\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_server.go:229 +0x2b8\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x1038721f0?, 0x14000de4fc0?}, 0x10120aaa4?)\n\tnet/http/server.go:2109 +0x38\nnet/http.serverHandler.ServeHTTP({0x10385c540?}, {0x1038721f0, 0x14000de4fc0}, 0x14001903800)\n\tnet/http/server.go:2947 +0x2c4\nnet/http.(*conn).serve(0x140020fc460, {0x103873820, 0x14001e3a210})\n\tnet/http/server.go:1991 +0x560\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3102 +0x444\n: panic [cosmos/cosmos-sdk@v0.46.7/baseapp/recovery.go:69] With gas wanted: '18446744073709551615' and gas used: '184519' : unknown request"
}
```

**Comment by loredanacirstea** [comment]
we use wazero now
