### ISSUE TITLE
bad pointer in frame wasmedge.NewFunction.func1 ; fatal error: invalid pointer found on stack

### ISSUE THREAD

**Issue by loredanacirstea** [ark-us/wasmx#83]
Got this while testing different wasmx commits. Subsequent test running was successful.

```
go test --count=1 -v -run KeeperTestSuite/TestEwasmOpcodes ./x/wasmx/keeper
```

```
=== RUN   TestKeeperTestSuite/TestEwasmOpcodes
runtime: bad pointer in frame github.com/second-state/WasmEdge-go/wasmedge.NewFunction.func1 at 0x140019e3700: 0x680
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0x104679336?, 0x10692e0a0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x16d4b6580 sp=0x16d4b6550 pc=0x102f84c30
runtime.adjustpointers(0x16d4b6920?, 0x29d807?, 0x1061191a9?, {0x106666bb8?, 0x10692e0a0?})
	/usr/local/go/src/runtime/stack.go:630 +0x1c4 fp=0x16d4b65c0 sp=0x16d4b6580 pc=0x102f9e894
runtime.adjustframe(0x16d4b6920, 0x16d4b6a18)
	/usr/local/go/src/runtime/stack.go:672 +0xa4 fp=0x16d4b6650 sp=0x16d4b65c0 pc=0x102f9e974
runtime.gentraceback(0x20000?, 0x0?, 0x0?, 0x14000554680, 0x0, 0x0, 0x7fffffff, 0x105916e60, 0x102f87574?, 0x0)
	/usr/local/go/src/runtime/traceback.go:334 +0x7e0 fp=0x16d4b6980 sp=0x16d4b6650 pc=0x102fac0f0
runtime.copystack(0x14000554680, 0x20000)
	/usr/local/go/src/runtime/stack.go:932 +0x2f8 fp=0x16d4b6b40 sp=0x16d4b6980 pc=0x102f9f148
runtime.shrinkstack(0x14000554680)
	/usr/local/go/src/runtime/stack.go:1214 +0x120 fp=0x16d4b6b60 sp=0x16d4b6b40 pc=0x102f9fce0
runtime.scanstack(0x14000554680, 0x1400006e640)
	/usr/local/go/src/runtime/mgcmark.go:775 +0xf0 fp=0x16d4b6d70 sp=0x16d4b6b60 pc=0x102f6c430
runtime.markroot.func1()
	/usr/local/go/src/runtime/mgcmark.go:240 +0xb4 fp=0x16d4b6dc0 sp=0x16d4b6d70 pc=0x102f6b2b4
runtime.markroot(0x1400006e640, 0x28, 0x1)
	/usr/local/go/src/runtime/mgcmark.go:213 +0x1fc fp=0x16d4b6e60 sp=0x16d4b6dc0 pc=0x102f6af6c
runtime.gcDrain(0x1400006e640, 0x7)
	/usr/local/go/src/runtime/mgcmark.go:1069 +0x424 fp=0x16d4b6ec0 sp=0x16d4b6e60 pc=0x102f6cfc4
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1327 +0x68 fp=0x16d4b6f10 sp=0x16d4b6ec0 pc=0x102f69098
runtime.systemstack()
	/usr/local/go/src/runtime/asm_arm64.s:243 +0x6c fp=0x16d4b6f20 sp=0x16d4b6f10 pc=0x102fb6aac

goroutine 37 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm64.s:200 +0x8 fp=0x14000115f40 sp=0x14000115f30 pc=0x102fb6a28
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1295 +0x224 fp=0x14000115fd0 sp=0x14000115f40 pc=0x102f68d54
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000115fd0 sp=0x14000115fd0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 1 [chan receive]:
runtime.gopark(0x1400117fa18?, 0x103063cc8?, 0x78?, 0xfa?, 0x102f58c3c?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x1400210f9f0 sp=0x1400210f9d0 pc=0x102f87574
runtime.chanrecv(0x1400013a2a0, 0x1400117faff, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x1400210fa80 sp=0x1400210f9f0 pc=0x102f52004
runtime.chanrecv1(0x10465bd00?, 0x10465bd00?)
	/usr/local/go/src/runtime/chan.go:442 +0x14 fp=0x1400210fab0 sp=0x1400210fa80 pc=0x102f51b74
testing.(*T).Run(0x14000f7fba0, {0x10465bd00?, 0x1c2cfdb55fb74?}, 0x105916630)
	/usr/local/go/src/testing/testing.go:1494 +0x314 fp=0x1400210fb50 sp=0x1400210fab0 pc=0x103068e24
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1846 +0x70 fp=0x1400210fba0 sp=0x1400210fb50 pc=0x10306ac10
testing.tRunner(0x14000f7fba0, 0x1400117fcb8)
	/usr/local/go/src/testing/testing.go:1446 +0x10c fp=0x1400210fbf0 sp=0x1400210fba0 pc=0x10306818c
testing.runTests(0x14001051c20?, {0x106df4f00, 0x3, 0x3}, {0xfb00000000000000?, 0xfb3b04aa90755fc4?, 0x106e37100?})
	/usr/local/go/src/testing/testing.go:1844 +0x3f0 fp=0x1400210fce0 sp=0x1400210fbf0 pc=0x10306aad0
testing.(*M).Run(0x14001051c20)
	/usr/local/go/src/testing/testing.go:1726 +0x4f0 fp=0x1400210fee0 sp=0x1400210fce0 pc=0x103069740
main.main()
	_testmain.go:53 +0x1d0 fp=0x1400210ff70 sp=0x1400210fee0 pc=0x10462e2a0
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x24c fp=0x1400210ffd0 sp=0x1400210ff70 pc=0x102f871ac
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400210ffd0 sp=0x1400210ffd0 pc=0x102fb90b4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000084fa0 sp=0x14000084f80 pc=0x102f87574
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xac fp=0x14000084fd0 sp=0x14000084fa0 pc=0x102f8740c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000084fd0 sp=0x14000084fd0 pc=0x102fb90b4
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000085770 sp=0x14000085750 pc=0x102f87574
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0x10c fp=0x140000857b0 sp=0x14000085770 pc=0x102f722dc
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x140000857d0 sp=0x140000857b0 pc=0x102f66838
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000857d0 sp=0x140000857d0 pc=0x102fb90b4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x106e3cc20?, 0x10546c800?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000085f50 sp=0x14000085f30 pc=0x102f87574
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x106e3cc20)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x5c fp=0x14000085f80 sp=0x14000085f50 pc=0x102f7022c
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:622 +0xac fp=0x14000085fb0 sp=0x14000085f80 pc=0x102f7083c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x14000085fd0 sp=0x14000085fb0 pc=0x102f667d8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000085fd0 sp=0x14000085fd0 pc=0x102fb90b4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xb8

goroutine 18 [finalizer wait]:
runtime.gopark(0x106e3e500?, 0x400000?, 0x0?, 0x0?, 0x102f66c9c?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000084580 sp=0x14000084560 pc=0x102f87574
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x120 fp=0x140000847d0 sp=0x14000084580 pc=0x102f65a60
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000847d0 sp=0x140000847d0 pc=0x102fb90b4
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x84

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1c2cfdee39f21?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000080740 sp=0x14000080720 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000807d0 sp=0x14000080740 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000807d0 sp=0x140000807d0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x1c2cfddbb0bca?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000080f40 sp=0x14000080f20 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000080fd0 sp=0x14000080f40 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000080fd0 sp=0x14000080fd0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1c2cfdee3a64a?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000114740 sp=0x14000114720 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140001147d0 sp=0x14000114740 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001147d0 sp=0x140001147d0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x106e74660?, 0x1?, 0xfb?, 0xd1?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000114f40 sp=0x14000114f20 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000114fd0 sp=0x14000114f40 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000114fd0 sp=0x14000114fd0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x106e74660?, 0x3?, 0x92?, 0xb8?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000115740 sp=0x14000115720 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140001157d0 sp=0x14000115740 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001157d0 sp=0x140001157d0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x106e74660?, 0x1?, 0x39?, 0xac?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000110740 sp=0x14000110720 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140001107d0 sp=0x14000110740 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001107d0 sp=0x140001107d0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x106e74660?, 0x3?, 0x59?, 0xe?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000081740 sp=0x14000081720 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140000817d0 sp=0x14000081740 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000817d0 sp=0x140000817d0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 51 [GC worker (idle)]:
runtime.gopark(0x1c2cfddb7d750?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000110f40 sp=0x14000110f20 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x14000110fd0 sp=0x14000110f40 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000110fd0 sp=0x14000110fd0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x106e74660?, 0x1?, 0x7e?, 0x5b?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000116740 sp=0x14000116720 pc=0x102f87574
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1235 +0xec fp=0x140001167d0 sp=0x14000116740 pc=0x102f68c1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001167d0 sp=0x140001167d0 pc=0x102fb90b4
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1159 +0x28

goroutine 10 [chan receive]:
runtime.gopark(0x14000db1b88?, 0x103063cc8?, 0xe8?, 0x1b?, 0x102f58c3c?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14002117b60 sp=0x14002117b40 pc=0x102f87574
runtime.chanrecv(0x1400013aaf0, 0x14000db1c6f, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x454 fp=0x14002117bf0 sp=0x14002117b60 pc=0x102f52004
runtime.chanrecv1(0x1400013d050?, 0x1400013d050?)
	/usr/local/go/src/runtime/chan.go:442 +0x14 fp=0x14002117c20 sp=0x14002117bf0 pc=0x102f51b74
testing.(*T).Run(0x14000f7fd40, {0x1054c6af9?, 0x14000f7fd40?}, 0x14000d938c0)
	/usr/local/go/src/testing/testing.go:1494 +0x314 fp=0x14002117cc0 sp=0x14002117c20 pc=0x103068e24
github.com/stretchr/testify/suite.runTests({0x105952990, 0x14000f7fd40}, {0x140010ed200?, 0x35, 0x40})
	/Users/user/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:242 +0x130 fp=0x14002117d30 sp=0x14002117cc0 pc=0x103d615d0
github.com/stretchr/testify/suite.Run(0x14000f7fd40, {0x10593bb40, 0x14000e58d20})
	/Users/user/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:215 +0x604 fp=0x14002117f10 sp=0x14002117d30 pc=0x103d60b74
mythos/v1/x/wasmx/keeper_test.TestKeeperTestSuite(0x0?)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/keeper_test.go:93 +0x6c fp=0x14002117f60 sp=0x14002117f10 pc=0x1046200dc
testing.tRunner(0x14000f7fd40, 0x105916630)
	/usr/local/go/src/testing/testing.go:1446 +0x10c fp=0x14002117fb0 sp=0x14002117f60 pc=0x10306818c
testing.(*T).Run.func1()
	/usr/local/go/src/testing/testing.go:1493 +0x2c fp=0x14002117fd0 sp=0x14002117fb0 pc=0x103068ecc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14002117fd0 sp=0x14002117fd0 pc=0x102fb90b4
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x300

goroutine 82 [select]:
runtime.gopark(0x14000087778?, 0x3?, 0x0?, 0x80?, 0x14000087762?)
	/usr/local/go/src/runtime/proc.go:363 +0xe4 fp=0x14000092e00 sp=0x14000092de0 pc=0x102f87574
runtime.selectgo(0x14000092f78, 0x1400008775c, 0x14000314000?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x688 fp=0x14000092f20 sp=0x14000092e00 pc=0x102f97e88
go.opencensus.io/stats/view.(*worker).start(0x14000314000)
	/Users/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x88 fp=0x14000092fb0 sp=0x14000092f20 pc=0x1042932a8
go.opencensus.io/stats/view.init.0.func1()
	/Users/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x28 fp=0x14000092fd0 sp=0x14000092fb0 pc=0x1042925d8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000092fd0 sp=0x14000092fd0 pc=0x102fb90b4
created by go.opencensus.io/stats/view.init.0
	/Users/user/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0xa4

goroutine 11 [GC assist marking (scan)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm64.s:200 +0x8 fp=0x140019e35a0 sp=0x140019e3590 pc=0x102fb6a28
runtime.gcAssistAlloc(0x14000554680)
	/usr/local/go/src/runtime/mgcmark.go:473 +0x1e8 fp=0x140019e3600 sp=0x140019e35a0 pc=0x102f6ba08
runtime.mallocgc(0x8, 0x10559c2a0, 0x0)
	/usr/local/go/src/runtime/malloc.go:906 +0x134 fp=0x140019e3670 sp=0x140019e3600 pc=0x102f58344
runtime.convT64(0x60000183a8f0)
	/usr/local/go/src/runtime/iface.go:382 +0x4c fp=0x140019e36a0 sp=0x140019e3670 pc=0x102f563cc
github.com/second-state/WasmEdge-go/wasmedge.NewFunction.func1(0x106e36b00?, 0x105916770?, 0x105668de0?)
	/Users/user/go/pkg/mod/github.com/loredanacirstea/!wasm!edge-go@v0.11.3-0.20230314131152-38caaf64a4b7/wasmedge/instance.go:336 +0x44 fp=0x140019e3710 sp=0x140019e36a0 pc=0x103af7f34
github.com/second-state/WasmEdge-go/wasmedge.NewFunction(0x14002070920, 0x1046677e9?, {0x105668de0?, 0x14002043500?}, 0x0?)
	/Users/user/go/pkg/mod/github.com/loredanacirstea/!wasm!edge-go@v0.11.3-0.20230314131152-38caaf64a4b7/wasmedge/instance.go:336 +0x4c fp=0x140019e3760 sp=0x140019e3710 pc=0x103af7e4c
mythos/v1/x/wasmx/vm.BuildEwasmEnv(0x104651060?)
	/Users/user/dev/blockchain/wasmx/x/wasmx/vm/ops_ewasm.go:827 +0x60c fp=0x140019e38b0 sp=0x140019e3760 pc=0x103c4ffcc
mythos/v1/x/wasmx/vm.InitiateEwasmTypeEnv(0x105636140?, 0x14000e5fc80?, 0x140020707b0?)
	/Users/user/dev/blockchain/wasmx/x/wasmx/vm/initiate.go:108 +0x24 fp=0x140019e3940 sp=0x140019e38b0 pc=0x103c41724
mythos/v1/x/wasmx/vm.initiateWasmDeps(0x14000554680?, 0x200000003?, {0x14001fe28c0, 0x1, 0x1076685b8?}, {0x140000111f8, 0x1, 0x1})
	/Users/user/dev/blockchain/wasmx/x/wasmx/vm/vm.go:76 +0x188 fp=0x140019e3a00 sp=0x140019e3940 pc=0x103c56cb8
mythos/v1/x/wasmx/vm.initiateWasmDeps(0x1055760c0?, 0x0?, {0x14001fe2910, 0x1, 0x14002056750?}, {0x140000111f8, 0x1, 0x1})
	/Users/user/dev/blockchain/wasmx/x/wasmx/vm/vm.go:66 +0x100 fp=0x140019e3ac0 sp=0x140019e3a00 pc=0x103c56c30
mythos/v1/x/wasmx/vm.InitiateWasm(0x105635360?, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x14001fe2910, 0x1, 0x1})
	/Users/user/dev/blockchain/wasmx/x/wasmx/vm/vm.go:52 +0x248 fp=0x140019e3bc0 sp=0x140019e3ac0 pc=0x103c56a38
mythos/v1/x/wasmx/vm.ExecuteWasmInterpreted({{0x10593e8f0, 0x1400019e008}, {0x10594d1f0, 0x14002082140}, {{0x0, 0x0}, {0x104651060, 0xd}, 0x5, {0x0, ...}, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/vm/vm.go:247 +0x4dc fp=0x140019e3f90 sp=0x140019e3bc0 pc=0x103c57abc
mythos/v1/x/wasmx/keeper.WasmxEngine.QueryExecute({{_, _}, _}, {{0x10593e8f0, 0x1400019e008}, {0x10594d1f0, 0x14002082140}, {{0x0, 0x0}, {0x104651060, ...}, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/vm.go:170 +0x2c4 fp=0x140019e45b0 sp=0x140019e3f90 pc=0x103c797c4
mythos/v1/x/wasmx/keeper.Keeper.query({{0x1059521b8, 0x140000e1d20}, {0x105926690, 0x14000fa9220}, {0x105926690, 0x0}, {{0x10594c850, 0x140000e1d20}, 0x14000133910, {0x105926690, ...}, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/contract.go:742 +0x890 fp=0x140019e6240 sp=0x140019e45b0 pc=0x103c65280
mythos/v1/x/wasmx/keeper.Keeper.Query({{0x1059521b8, 0x140000e1d20}, {0x105926690, 0x14000fa9220}, {0x105926690, 0x0}, {{0x10594c850, 0x140000e1d20}, 0x14000133910, {0x105926690, ...}, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/contract.go:70 +0x74 fp=0x140019e66d0 sp=0x140019e6240 pc=0x103c5bf64
mythos/v1/x/wasmx/keeper.Keeper.SmartContractCall({{0x1059521b8, 0x140000e1d20}, {0x105926690, 0x14000fa9220}, {0x105926690, 0x0}, {{0x10594c850, 0x140000e1d20}, 0x14000133910, {0x105926690, ...}, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/query.go:204 +0x534 fp=0x140019e7e70 sp=0x140019e66d0 pc=0x103c73b94
mythos/v1/x/wasmx/keeper.(*Keeper).SmartContractCall(0x1058293e0?, {0x10593f840?, 0x14002062dc0?}, 0x103916b7c?)
	<autogenerated>:1 +0x7c fp=0x140019e8140 sp=0x140019e7e70 pc=0x103c7f69c
mythos/v1/x/wasmx/types._Query_SmartContractCall_Handler({0x105905c00?, 0x140014ecf20}, {0x10593f840, 0x14002062dc0}, 0x14001fe2870, 0x0)
	/Users/user/dev/blockchain/wasmx/x/wasmx/types/query.pb.go:1525 +0x170 fp=0x140019e81a0 sp=0x140019e8140 pc=0x103b28af0
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x10593e8f0, 0x1400019e008}, {0x10594d1f0, 0x14002082140}, {{0x0, 0x0}, {0x104651060, 0xd}, 0x5, {0x0, ...}, ...}, ...}, ...)
	/Users/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/grpcrouter.go:82 +0x144 fp=0x140019e8540 sp=0x140019e81a0 pc=0x103916c24
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0x140014c5880, 0x140014cfb30, {{0x1400000d500, 0xf4, 0xf4}, {0x1046996b8, 0x28}, 0x5, 0x0})
	/Users/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:562 +0xfc fp=0x140019e9000 sp=0x140019e8540 pc=0x1039106cc
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0x140014c5880, {{0x1400000d500, 0xf4, 0xf4}, {0x1046996b8, 0x28}, 0x5, 0x0})
	/Users/user/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:406 +0x8bc fp=0x140019e94d0 sp=0x140019e9000 pc=0x10390f10c
mythos/v1/x/wasmx/keeper/testutil.AppContext.WasmxQueryRawNoCheck({{0x105949b08, 0x14000e58d20}, 0x14000260000, 0x1400108f8c0, {{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/testutil/app_context.go:451 +0x220 fp=0x140019e9770 sp=0x140019e94d0 pc=0x1045e52e0
mythos/v1/x/wasmx/keeper/testutil.AppContext.WasmxQueryRaw({{0x105949b08, 0x14000e58d20}, 0x14000260000, 0x1400108f8c0, {{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/testutil/app_context.go:426 +0xc0 fp=0x140019e9bd0 sp=0x140019e9770 pc=0x1045e4eb0
mythos/v1/x/wasmx/keeper/testutil.AppContext.WasmxQuery({{0x105949b08, 0x14000e58d20}, 0x14000260000, 0x1400108f8c0, {{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/testutil/app_context.go:421 +0xc0 fp=0x140019e9e80 sp=0x140019e9bd0 pc=0x1045e4cb0
mythos/v1/x/wasmx/keeper_test.(*KeeperTestSuite).TestEwasmOpcodes(0x14000e58d20)
	/Users/user/dev/blockchain/wasmx/x/wasmx/keeper/classic_test.go:185 +0x146c fp=0x140019ed630 sp=0x140019e9e80 pc=0x1045ecd9c
runtime.call16(0x140011564b0, 0x14000133378, 0x0, 0x0, 0x0, 0x8, 0x14001c5fb70)
	/usr/local/go/src/runtime/asm_arm64.s:478 +0x78 fp=0x140019ed650 sp=0x140019ed630 pc=0x102fb6f38
runtime.reflectcall(0x10590ece0?, 0x14000e58d20?, 0x1?, 0x465ac07?, 0x1?, 0x12?, 0x10590ece0?)
	<autogenerated>:1 +0x34 fp=0x140019ed690 sp=0x140019ed650 pc=0x102fbaa34
reflect.Value.call({0x1400002d140?, 0x14000133378?, 0x3e8?}, {0x104642427, 0x4}, {0x14001b69e68, 0x1, 0x1344c2080?})
	/usr/local/go/src/reflect/value.go:584 +0x688 fp=0x140019edd00 sp=0x140019ed690 pc=0x103020448
reflect.Value.Call({0x1400002d140?, 0x14000133378?, 0x14000e58d20?}, {0x14001b69e68?, 0x1030680b3?, 0x1063c9e58?})
	/usr/local/go/src/reflect/value.go:368 +0x90 fp=0x140019edd80 sp=0x140019edd00 pc=0x10301fbd0
github.com/stretchr/testify/suite.Run.func1(0x140005544e0)
	/Users/user/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:197 +0x3e4 fp=0x140019edf60 sp=0x140019edd80 pc=0x103d610d4
testing.tRunner(0x140005544e0, 0x14000d938c0)
	/usr/local/go/src/testing/testing.go:1446 +0x10c fp=0x140019edfb0 sp=0x140019edf60 pc=0x10306818c
testing.(*T).Run.func1()
	/usr/local/go/src/testing/testing.go:1493 +0x2c fp=0x140019edfd0 sp=0x140019edfb0 pc=0x103068ecc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140019edfd0 sp=0x140019edfd0 pc=0x102fb90b4
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x300
FAIL	mythos/v1/x/wasmx/keeper	0.779s
FAIL
user@Loredanas-MacBook-Pro-M1 wasmx %
```

**Comment by loredanacirstea** [comment]
we use wazero
